on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.0
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Reviung34)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=reviung34 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Reviung34 DTS File
        if: ${{ always() }}
        run: |
          if [ -f "build/zephyr/nice_nano_v2.dts.pre.tmp" ]; then cat -n build/zephyr/nice_nano_v2.dts.pre.tmp; fi
          if [ -f "build/zephyr/zephyr.dts" ]; then cat -n build/zephyr/zephyr.dts; fi
      - name: Reviung34 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 reviung34_nice_nano_v2.uf2
      - name: Archive (Reviung34)
        uses: actions/upload-artifact@v2
        with:
          name: reviung34-firmware-${{github.run_number}}
          path: reviung34_nice_nano_v2.uf2
